### ISSUE TITLE
システムにより終了されてしまう問題

### ISSUE THREAD

**Issue by diontools** [diontools/DoNotSpeak#6]
## 問題
長期間使用しているとシステムによりプロセスがキルされることがある。
システムがバックアップを始めると発生する（恐らく、起動しているアプリはバックアップが延期され、深夜にアプリが強制終了されてバックアップが動作する）。
1秒後に再起動（START_STICKY）されるが、`onCreate`の後に`onDestroy`が呼ばれ、`onStartCommand`が呼ばれないことがある。

## 対策
* ~~クイック設定を開いたときにキルされた後だった場合は有効にする。~~ アプリを手動停止したときと区別できないため行わない。
* `AlarmManager`を使用して1時間後に起動確認する。([AlarmManager#set](https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20android.app.PendingIntent)))

**Comment by diontools** [comment]
`onStartCommand`が呼ばれないパターン `onCreate -> onDestroy`
```
2021/09/28 03:12:12.495 onCreate
2021/09/28 03:12:12.497 applySettings
2021/09/28 03:12:12.525 onDestroy
2021/09/28 03:12:12.593 onAudioDevicesAdded
2021/09/28 03:12:12.593 added device: android.media.AudioDeviceInfo@21 type: 1
2021/09/28 03:12:12.594 added device: android.media.AudioDeviceInfo@22 type: 2
2021/09/28 03:12:12.594 added device: android.media.AudioDeviceInfo@27 type: 18
2021/09/28 03:12:12.594 added device: android.media.AudioDeviceInfo@2f type: 15
2021/09/28 03:12:12.594 added device: android.media.AudioDeviceInfo@2c type: 18
2021/09/28 03:12:12.595 added device: android.media.AudioDeviceInfo@30 type: 15
2021/09/28 03:12:12.595 added device: android.media.AudioDeviceInfo@2d type: 16
2021/09/28 03:12:12.595 update forceMute:false
2021/09/28 03:12:12.595 unmute
2021/09/28 03:12:12.595 cancel timer
```

**Comment by diontools** [comment]
深夜3時台にフルバックアップが行われ、

```
10-15 03:38:26.936  1453 10494 D KeyValueBackupTask: Starting full backups for: [io.github.diontools.donotspeak]
10-15 03:38:26.938  1453 10506 I PFTBT   : Initiating full-data transport backup of io.github.diontools.donotspeak token: 307918453
10-15 03:38:26.941 28089 29250 I Backup  : [GmsBackupTransport] Attempt to do full backup on io.github.diontools.donotspeak

10-15 03:38:27.002 28089 29250 I Backup  : [FullBackupSession] Using encrypted processor for io.github.diontools.donotspeak

10-15 03:38:27.072  1453 10509 D BackupManagerService: awaiting agent for ApplicationInfo{33c0201 io.github.diontools.donotspeak}
10-15 03:38:27.073 23111 23111 V ActivityThread: handleCreateBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{59df8e1 io.github.diontools.donotspeak} backupAgent=null mode=1 userId=0}
10-15 03:38:27.076 23111 23111 V ActivityThread: Initializing agent class android.app.backup.FullBackupAgent
10-15 03:38:27.076 28089  2829 I Backup  : [EncryptedFullBackupTask] Found previous chunk listing for io.github.diontools.donotspeak
10-15 03:38:27.079  1453  4506 D BackupManagerService: agentConnected pkg=io.github.diontools.donotspeak agent=android.os.BinderProxy@6ef58a6
10-15 03:38:27.079  1453 10509 I BackupManagerService: got agent android.app.IBackupAgent$Stub$Proxy@74f82e7
10-15 03:38:27.079  1453 10509 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
10-15 03:38:27.133  1453 10506 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
10-15 03:38:27.151  1453 10510 I chatty  : uid=1000 system_server expire 1 line
10-15 03:38:27.151  1453 10510 I BackupRestoreController: Getting widget state for user: 0
10-15 03:38:27.151  1453 10510 D BackupManagerService: Calling doFullBackup() on io.github.diontools.donotspeak
10-15 03:38:27.151  1453 10510 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
10-15 03:38:27.157 23111 30342 I file_backup_helper:    Name: apps/io.github.diontools.donotspeak/sp/donotspeak_pref.xml.xml
10-15 03:38:27.165 23111 23111 V ActivityThread: handleDestroyBackupAgent: CreateBackupAgentData{appInfo=ApplicationInfo{7a0421d io.github.diontools.donotspeak} backupAgent=null mode=0 userId=0}
```

プロセスが終了する。

```
10-15 03:38:27.254  1453  4501 I ActivityManager: Process io.github.diontools.donotspeak (pid 23111) has died: vis FGS 
10-15 03:38:27.263  1453  4501 W ActivityManager: Scheduling restart of crashed service io.github.diontools.donotspeak/.DNSService in 1000ms
10-15 03:38:27.264  1453  4501 W ActivityManager: Scheduling restart of crashed service io.github.diontools.donotspeak/.DNSTileService in 10999ms
```

その後バックアップは完了。

```
10-15 03:38:28.043 28089 29250 I Backup  : [GmsBackupTransport] Backup finished for io.github.diontools.donotspeak
```

アプリがアイドル状態になりサービス停止。

```
10-15 03:38:28.282  1453  3638 W ActivityManager: Stopping service due to app idle: u0a358 -1d16h18m56s780ms io.github.diontools.donotspeak/.DNSService
```

サービスが自動再起動。

```
10-15 03:38:28.298  1453  1643 I ActivityManager: Start proc 10537:io.github.diontools.donotspeak/u0a358 for service {io.github.diontools.donotspeak/io.github.diontools.donotspeak.DNSService}
```

`BluetoothAdapter.getProfileProxy`でリーク検出。

```
10-15 03:38:28.662 10537 10537 E ActivityThread: Service io.github.diontools.donotspeak.DNSService has leaked ServiceConnection android.bluetooth.BluetoothProfileConnector$2@8524846 that was originally bound here
10-15 03:38:28.662 10537 10537 E ActivityThread: android.app.ServiceConnectionLeaked: Service io.github.diontools.donotspeak.DNSService has leaked ServiceConnection android.bluetooth.BluetoothProfileConnector$2@8524846 that was originally bound here
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1856)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1728)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1707)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1728)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1682)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:736)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.bluetooth.BluetoothProfileConnector.doBind(BluetoothProfileConnector.java:90)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.bluetooth.BluetoothProfileConnector.connect(BluetoothProfileConnector.java:130)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.bluetooth.BluetoothA2dp.<init>(BluetoothA2dp.java:225)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:2529)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at io.github.diontools.donotspeak.DNSService.onCreate(Unknown Source:218)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4273)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ActivityThread.access$1900(ActivityThread.java:239)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2029)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.os.Looper.loop(Looper.java:214)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:7899)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-15 03:38:28.662 10537 10537 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:960)
```

**Comment by diontools** [comment]
`BluetoothAdapter.getProfileProxy`のリークを解決したが、依然として、`onStartCommand`が呼ばれず`onDestroy`されてしまう。
結局のところ`AlarmManager`を利用して定期的に起動確認することが必要であると思われる。

**Comment by diontools** [comment]
`onCreate -> onDestroy`後に`AlarmManager`からの呼び出しが行われないことを観測。原因不明。🤔

**Comment by diontools** [comment]
`PendingIntent.getBroadcast()`の`context`にサービスのインスタンスを渡しているので、`onDestroy`後はサービスのライフサイクルから外れてしまっている。`getApplicationContext()`を試してみる。

参考: https://qiita.com/iduchikun/items/34b3ae26cfc438e7e5dc

**Comment by diontools** [comment]
残念ながら再発。ログを記録し観察を続行する。

**Comment by diontools** [comment]
マニフェストの`intent-filter`に`<action android:name="${applicationId}.REBOOT" />`を記述することで解決したかもしれない。経過観察中。

**Comment by diontools** [comment]
残念ながら復帰せず。`onDestroy`が呼ばれる場合、起動時にログが追記されるのでプロセスは生きていると考えられる。

**Comment by diontools** [comment]
エミュレーター上で開発者オプションの「実行中のサービス」から`DNSService`を停止させても再現せず。

**Comment by diontools** [comment]
`PendingIntent.getBroadcast`で指定していた`PendingIntent.FLAG_CANCEL_CURRENT`を`0`にすることで解決した。

**Comment by diontools** [comment]
v1.7.0で解決済み
